import React from 'react';
import './FAQ.css';

function FAQ() {
  const faqItems = [
    {
      question: "What is Jesus, Guide Me?",
      answer: "Jesus, Guide Me is a chat application that simulates a conversation with Jesus, offering guidance and comfort based on biblical teachings."
    },
    {
      question: "Are the answers really from Jesus?",
      answer: "No, the answers are generated by artificial intelligence based on teachings attributed to Jesus in the Bible."
    },
    {
      question: "Can I trust the advice given?",
      answer: "Although the advice is based on biblical teachings, this app does not replace professional spiritual guidance or medical advice."
    },
    {
      question: "Are my conversations private?",
      answer: "Yes, your conversations are private and not shared. However, they are stored locally on your device."
    }
  ];

  return (
    <div className="faq-container">
      <h2>Frequently Asked Questions</h2>
      {faqItems.map((item, index) => (
        <div key={index} className="faq-item">
          <h3>{item.question}</h3>
          <p>{item.answer}</p>
        </div>
      ))}
    </div>
  );
}

export default FAQ;